config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pets # ==> create restful routes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat rabbit snake turtle)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def create
  end

  def new
    @new_pet = Pet.new #blank instance
  end

  def edit
    @edited_pet = Pet.find(params[:id])
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="row justify-content-center align-item-center">
  <div class="col-6">
    <%= simple_form_for(pet) do |f| %>
      <%= f.input :name, label: 'Type the pet name' %>

      <%= f.input :address, placeholder: '1 Pet Road' %>

      <%= f.input :found_on %>

      <% if pet.id %>
        <%= f.button :submit, 'Update' , class: 'btn btn-primary' %>
      <% else %>
        <%= f.button :submit, 'Create' , class: 'btn btn-primary' %>
      <% end %>
    <% end %> 
  </div>
</div>

app/views/pets/edit.html.erb
<h2 class="text-center">Pets#edit</h2>

<%= render "form", pet: @edited_pet  %>

app/views/pets/index.html.erb
<h1>All pets</h1>

<%= link_to 'Found Pet', new_pet_path, class: 'btn btn-info btn-lg btn-block my-3' %>

<div class="row">
<% @pets.each do |pet| %>
<div class="col-4">
  <div class="card my-3">
    <div class="card-body">
      <h5 class="card-title"><%= pet.name %></h5>
      <p class="card-text"><%= pet.address %> - found on <%= pet.found_on %></p>
      <%= link_to 'View', pet_path(pet), class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<% end %>   
</div>

app/views/pets/new.html.erb
<h2 class="text-center">Found a pet</h1>

<%= render "form", pet: @new_pet %>

app/views/pets/show.html.erb
<div>
  <h2><%= @pet.name %>(<%= @pet.species %>)</h2>
  <p><%= @pet.address %></p>
  <small>found on <%= @pet.found_on %></small>
</div>